language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - "pip install ."
  - "pip install -r requirements.txt"
script: unit2 -v
notifications:
  email: 
    - petergoldsborough@hotmail.com
after_success:
  - coveralls